version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    ports:
      - "7474:7474" # Puerto para el navegador de Neo4j
      - "7687:7687" # Puerto para conexiones Bolt
    environment:
      - NEO4J_AUTH=neo4j/Jr20020194 # Usuario y contraseña
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
